### ISSUE TITLE
.

### ISSUE THREAD

**Issue by RuiMao1988** [kolloldas/torchnlp#4]

**Comment by RuiMao1988** [comment]
I tried to fix the local data issue. But it seems another one appears after the local data can be processed in the first epoch. 

INFO:torchnlp.common.train:Parameters: 464167(trainable), 5303101(non-trainable)
INFO:torchnlp.common.train:Early stopping for highest value of validation F1 after 5 epochs
INFO:torchnlp.common.train:Epoch 1 (0)
INFO:torchnlp.common.train:Train Loss: 42.23825                                                          
Traceback (most recent call last):                                                                       
  File "<stdin>", line 1, in <module>
  File "/home/rui/metaphor_identification/torchnlp/torchnlp/tasks/sequence_tagging/main.py", line 71, in train
    best_cp, _ = trainer.train(num_epochs, early_stopping=early_stopping)
  File "/home/rui/metaphor_identification/torchnlp/torchnlp/common/train.py", line 199, in train
    eval_metrics = self.evaluator.evaluate(self.model)
  File "/home/rui/metaphor_identification/torchnlp/torchnlp/common/evaluation.py", line 48, in evaluate
    r = m.results(total_loss)
  File "/home/rui/metaphor_identification/torchnlp/torchnlp/common/evaluation.py", line 213, in results
    'precision': precision,
UnboundLocalError: local variable 'precision' referenced before assignment

**Comment by kolloldas** [comment]
Thanks Rui for spotting this bug! Looks like I missed initializing the metrics variables. I've pushed a fix. Please try with the updated code and let me know if it solved the problem for you.
